"""auto

Revision ID: 7a66d51b4b28
Revises: 
Create Date: 2026-06-05 17:46:32.039052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a66d51b4b28'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geoname',
    sa.Column('geonameid', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('asciiname', sa.Text(), nullable=False),
    sa.Column('feature_class', sa.String(length=1), nullable=False),
    sa.Column('feature_code', sa.String(length=10), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('admin1_code', sa.String(length=20), nullable=True),
    sa.Column('admin2_code', sa.String(length=80), nullable=True),
    sa.Column('population', sa.BigInteger(), nullable=False),
    sa.Column('latitude', sa.Double(), nullable=True),
    sa.Column('longitude', sa.Double(), nullable=True),
    sa.Column('timezone', sa.String(length=40), nullable=True),
    sa.Column('modification_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('geonameid')
    )
    op.create_index(op.f('ix_geoname_country_code'), 'geoname', ['country_code'], unique=False)
    op.create_table('alternate_name',
    sa.Column('alternate_name_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('geonameid', sa.Integer(), nullable=False),
    sa.Column('isolanguage', sa.String(length=7), nullable=True),
    sa.Column('alternate_name', sa.Text(), nullable=False),
    sa.Column('is_preferred_name', sa.Boolean(), nullable=False),
    sa.Column('is_short_name', sa.Boolean(), nullable=False),
    sa.Column('is_colloquial', sa.Boolean(), nullable=False),
    sa.Column('is_historic', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['geonameid'], ['geoname.geonameid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alternate_name_id')
    )
    op.create_index(op.f('ix_alternate_name_geonameid'), 'alternate_name', ['geonameid'], unique=False)
    op.create_index(op.f('ix_alternate_name_isolanguage'), 'alternate_name', ['isolanguage'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alternate_name_isolanguage'), table_name='alternate_name')
    op.drop_index(op.f('ix_alternate_name_geonameid'), table_name='alternate_name')
    op.drop_table('alternate_name')
    op.drop_index(op.f('ix_geoname_country_code'), table_name='geoname')
    op.drop_table('geoname')
    # ### end Alembic commands ###
